version: '2'
services:
  mongo:
    image: "mongo:3.0"
    ports:
      - "27017:27017"
    expose:
      - "27017"
  myownwebtest-storage:
    build: https://github.com/chenweiLabri/myownwebtest-storage.git
    image: "wei/wat_storage"
    ports:
      - "8086:8086"
    depends_on:
      - "mongo"